### ISSUE TITLE
Pagination Not Working

### ISSUE THREAD

**Issue by dirtystylus** [Wilto/Dynamic-Carousel#36]
Latest commit fd9af96 appears to have re-enabled the core next/prev naviation, but pagination still appears to be disabled. I'm testing the demo.html file with the second example (pagination both numbered and icon-based don't affect the carousel).

**Comment by adamnorwood** [comment]
I just started playing with this plugin -- loving it so far! But I ran into the same "pagination not working" issue, and given that it's not working in the demo.html for me I'm assuming that it's a bug. This appears to be fixed by @boberetezeke's pull request 8a3a2384fcc1a31e9415fdf049be7227dcef8145 suggestion of swapping out the true for false in that if statement?

**Comment by Wilto** [comment]
Just merged this in—should be all set now! Sorry for the delay.
